FROM python:3.8

# Install sagemaker-training toolkit to enable SageMaker Python SDK
RUN pip install sagemaker-training auto-sklearn==0.14.0 joblib==1.1.0 pandas==1.3.4 matplotlib

# Copies the training code inside the container
COPY container /opt/ml/code/

# Defines train.py as script entrypoint
ENV SAGEMAKER_PROGRAM train.py